version: "3.9"
services:
  pair-dev-db:
    image: postgres
    restart: always
    container_name: pair-dev
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes: postgres
