version: "3.9"

services:
  pair-dev:
    image: postgres
    container_name: pair-dev
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
